<?php
/**
 * Copyright (c) CopeX GmbH 2017.
 */

class CopeX_AttributesInMails_Block_Attributes extends Mage_Core_Block_Template
{

    protected function _beforeToHtml()
    {

        $productId = $this->getParentBlock()->getItem()->getProduct()->getId(); //for order emails
        //$productId = $_item->getProductId(); //for invoice emails
        $product = Mage::getModel('catalog/product')->load($productId);
        $this->setProduct($product);
        $productAttributes = $product->getAttributes();


        //Get a list of all PRODUCT ATTRIBUTES you want to show in this array...
        $attributeCollection = Mage::getResourceModel('catalog/product_attribute_collection')
            ->setItemObjectClass('catalog/resource_eav_attribute')
            ->addFieldToFilter('additional_table.is_visible_on_checkout', 1);
        foreach ($attributeCollection as $attribute) {
            $_displayedAttributes[] = $attribute->getAttributeCode();
        }
        //remove unused attributes from array
        foreach($productAttributes as $attribute){
            $attributeCode = $attribute->getAttributeCode();
            if (in_array($attributeCode, $_displayedAttributes)){
                $displayedAttributes[$attributeCode] = $attribute;
            };
        }



        $this->setData('displayed_attributes', $displayedAttributes);
        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }


}